[build-system]
requires = ["setuptools", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[project]
name = "mujoco-toolbox"
version = "0.0.1"
authors = [
    { name = "MGross21", email = "MGross21@TODO.com" }
]
description = "A modern package to handle Mujoco environments"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "mujoco==3.2.7",
    "numpy==2.2.3",
    "scipy==1.15.2",
    "matplotlib==3.9.2",
    "pyyaml==6.0.2",
    "mediapy==1.2.2",
    "tqdm==4.67.1",
    "ipywidgets==8.1.5",
    "ffmpeg==1.4",
    "trimesh==4.6.2",
    "screeninfo==0.8.1"
]

[project.urls]
homepage = "https://github.com/MGross21/mujoco-toolbox"
bug_tracker = "https://github.com/MGross21/mujoco-toolbox/issues"

[tool.setuptools]
packages = ["mujoco_toolbox"]  # Explicitly include only mujoco_toolbox