[build-system]
requires = ["setuptools", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[project]
name = "mujoco-toolbox"
version = "0.0.1"
authors = [
    { name = "MGross21", email = "MGross21@TODO.com" }
]
description = "A modern package to handle Mujoco environments"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "mujoco",
    "numpy",
    "scipy",
    "matplotlib",
    "pyyaml",
    "mediapy",
    "tqdm",
    "ipywidgets",
    "ffmpeg",
    "trimesh",
    "screeninfo"
]

[project.urls]
homepage = "https://github.com/MGross21/mujoco-toolbox"
bug_tracker = "https://github.com/MGross21/mujoco-toolbox/issues"

[tool.setuptools]
packages = ["mujoco_toolbox"]  # Explicitly include only mujoco_toolbox