[build-system]
requires = ["setuptools", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[project]
name = "MujocoHandler"
version = "0.0.1"
authors = [
    { name = "MGross21", email = "MGross21<at>MGross21.com" }
]
description = "A modern package to handle Mujoco environments"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
dependencies = [
    "mujoco",
    "numpy",
    "scipy",
    "matplotlib",
    "yaml",
    "mediapy",
    "tqdm",
    "ipywidgets"
]

[project.urls]
homepage = "https://github.com/MGross21/MujocoHandler"
bug_tracker = "https://github.com/MGross21/MujocoHandler/issues"
