name: CI Workflow
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Call Lint Workflow
        uses: ./.github/workflows/lint.yml
        continue-on-error: true  # Allow lint to fail without stopping the workflow

  type-checking:
    name: Type Checking
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Call Type Checking Workflow
        uses: ./.github/workflows/type-checking.yml
        continue-on-error: true  # Allow type-checking to fail without stopping the workflow

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: type-checking
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Call Test Workflow
        uses: ./.github/workflows/test.yml
        continue-on-error: false  # Fail if tests fail (optional, depending on your requirements)