name: Integration Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11', '3.12','3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libosmesa6-dev \
          xvfb \
          libglew-dev \
          patchelf \
          ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pip install ruff mypy pytest
        pip install . --no-cache-dir

    - name: Set Mujoco environment variables
      run: |
        echo "MUJOCO_GL=osmesa" >> $GITHUB_ENV
        echo "PYOPENGL_PLATFORM=osmesa" >> $GITHUB_ENV

    - name: Run Ruff Linter
      run: |
        ruff check .
        ruff format --check .

    - name: Run Type Checking
      run: |
        mypy .

    - name: Run Tests
      run: |
        pytest tests/ --cov=your_package_name --cov-report=xml --maxfail=3 -v

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true