name: CI Workflow
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      python-versions: ['3.10', '3.11', '3.12', '3.13']

  lint:
    uses: ./.github/workflows/lint.yml
    needs: setup

  type-checking:
    uses: ./.github/workflows/type-checking.yml
    needs: lint

  test:
    uses: ./.github/workflows/test.yml
    needs: type-checking