name: CI Workflow
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13"]'

  lint:
    name: Lint
    needs: setup
    uses: ./.github/workflows/lint.yml
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write

  type-checking:
    name: Type Checking
    needs: lint
    uses: ./.github/workflows/type-checking.yml
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write

  test:
    name: Test
    needs: type-checking
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read