name: CI Status

on:
  push:
    branches: [main]
    paths: ['**.py', 'pyproject.toml', '.github/workflows/**']
  pull_request:
    branches: [main]
    paths: ['**.py', 'pyproject.toml', '.github/workflows/**']
  workflow_dispatch:

jobs:
  ci-status:
    runs-on: ubuntu-latest
    steps:
      - name: CI Status Check
        run: echo "All CI workflows must pass independently"