name: CI Workflow
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Call Lint Workflow
        uses: ./.github/workflows/lint.yml

  type-checking:
    name: Type Checking
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Call Type Checking Workflow
        uses: ./.github/workflows/type-checking.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [type-checking]
    steps:
      - name: Call Test Workflow
        uses: ./.github/workflows/test.yml