name: Lint and Format
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Linters
        run: |
          ruff check . --fix --unsafe-fixes
          ruff format . --check
          black . --check
          isort . --check-only
          flake8 .
          bandit -r . --quiet
          pylint **/*.py

      - name: Commit Fixes if Needed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-fix lint issues"
            git push origin ${{ github.head_ref }}
          fi
