name: Lint and Format
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort flake8 bandit pylint

      - name: Run Linters
        run: |
          ruff check . --fix --unsafe-fixes
          ruff format . --check
          black . --check
          isort . --check-only
          flake8 .
          bandit -r . --quiet
          pylint **/*.py

      - name: Commit Fixes if Needed
        if: github.event_name == 'pull_request'  # Only run on PRs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-fix issues"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.head_ref }}
          fi
