name: PyPI Package
permissions:
  contents: read

on:
  push:
    branches:
      - main  # Triggers the workflow when changes are pushed to the `main` branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install build tool
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} 
        run: |
          twine upload dist/*