name: Setup Python Environment
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      python-versions:
        description: "List of Python versions to test"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          clean: true     # Ensure clean workspace

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry  # Enable Poetry cache for faster installs

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ matrix.python-version }}-pip-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
          restore-keys: |
            python-${{ matrix.python-version }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libosmesa6-dev \
            xvfb \
            libglew-dev \
            patchelf \
            ffmpeg

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Install package
        run: |
          pip install . --no-cache-dir

      - name: Set Mujoco environment variables
        run: |
          echo "MUJOCO_GL=osmesa" >> $GITHUB_ENV
          echo "PYOPENGL_PLATFORM=osmesa" >> $GITHUB_ENV

      - name: Verify Environment Setup
        run: |
          python --version
          poetry --version
          pytest --version
          mypy --version