name: Test
permissions:
  contents: read

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          pytest tests/ --cov=your_package_name --cov-report=xml --maxfail=3 -v

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true