name: Run Tests
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    needs: type-checking

    steps:
      - name: Run Tests
        run: |
          pytest tests/ --cov=your_package_name --cov-report=xml --maxfail=3 -v

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true