name: Type Checking and Annotation
permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-3.10-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            python-3.10-pip-

      - name: Install Poetry and type checking tools
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
          poetry add --group dev mypy pytypes

      - name: Run Type Checking with MyPy
        id: mypy_check
        continue-on-error: true
        run: |
          poetry run mypy .

      - name: Automatically Add Type Annotations with Pytypes
        if: steps.mypy_check.outcome == 'failure'
        run: |
          poetry run pytypes --check --annotate .

      - name: Commit Fixes if Needed
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-fix type issues with Pytypes"
            git push origin HEAD:${{ github.head_ref }}
          fi