name: Type Checking and Annotation

on:
  workflow_call:

jobs:
  type-checking:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Run Type Checking with MyPy
        run: |
          mypy . || echo "MyPy found errors"
        continue-on-error: true

      - name: Automatically Add Type Annotations with Pytypes (if MyPy errors found)
        if: failure()  # Only run if MyPy found errors
        run: |
          pytypes --check --annotate .

      - name: Commit all Changes (Ruff and Pytypes) if needed
        if: failure()  # Only run if changes were made by Ruff or Pytypes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --exit-code || git commit -m "chore: auto-fix lint issues and add type annotations"
          git push origin ${{ github.head_ref }}