name: Type Checking and Annotation
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:

jobs:
  type-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Type Checking with MyPy
        run: |
          mypy . || echo "MyPy found errors"
        continue-on-error: true

      - name: Automatically Add Type Annotations with Pytypes (if MyPy errors found)
        if: failure()
        run: |
          pytypes --check --annotate .

      - name: Commit all Changes (Ruff and Pytypes) if needed
        if: failure()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --exit-code || git commit -m "chore: auto-fix lint issues and add type annotations"
          git push origin ${{ github.head_ref }}